# -*- coding: utf-8 -*-
"""
/***************************************************************************
 AlbertsPlugin
                                 A QGIS plugin
 Plugin lets you get some informations about destination choices of points.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2022-06-08
        copyright            : (C) 2022 by Albert Kalinowski
        email                : 01159952@pw.edu.pl
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load AlbertsPlugin class from file AlbertsPlugin.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .alberts_plugin import AlbertsPlugin
    return AlbertsPlugin(iface)
